// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwEHPL9P0RbFYdIYcajf6gr9BBO5oh_A',
    appId: '1:154608703967:web:171eebb76dfcbe9bdf0c6a',
    messagingSenderId: '154608703967',
    projectId: 'test-5bb76',
    authDomain: 'test-5bb76.firebaseapp.com',
    databaseURL: 'https://test-5bb76-default-rtdb.firebaseio.com',
    storageBucket: 'test-5bb76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dQ0OQbbwIPwfzmi_ttIzUQIQSpgvYqE',
    appId: '1:154608703967:ios:c6d9ab05715ee54adf0c6a',
    messagingSenderId: '154608703967',
    projectId: 'test-5bb76',
    databaseURL: 'https://test-5bb76-default-rtdb.firebaseio.com',
    storageBucket: 'test-5bb76.appspot.com',
    iosClientId: '154608703967-hf46bou3lig636gh071mjj5i8plmqa4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_dQ0OQbbwIPwfzmi_ttIzUQIQSpgvYqE',
    appId: '1:154608703967:ios:c6d9ab05715ee54adf0c6a',
    messagingSenderId: '154608703967',
    projectId: 'test-5bb76',
    databaseURL: 'https://test-5bb76-default-rtdb.firebaseio.com',
    storageBucket: 'test-5bb76.appspot.com',
    iosClientId: '154608703967-hf46bou3lig636gh071mjj5i8plmqa4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterprojects',
  );
}
